//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LopHoc
    {
        public int LopHocId { get; set; }
        public int KhoiLopId { get; set; }
        public string Ten { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DM_KhoiLop DM_KhoiLop { get; set; }
    }
}
