//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_MonHoc()
        {
            this.DM_GiaoVien = new HashSet<DM_GiaoVien>();
            this.DM_PhongHocBoMon = new HashSet<DM_PhongHocBoMon>();
            this.DM_ThietBiToiThieu = new HashSet<DM_ThietBiToiThieu>();
            this.TB_PhieuMuonPhong = new HashSet<TB_PhieuMuonPhong>();
            this.TB_PhieuMuonTB = new HashSet<TB_PhieuMuonTB>();
            this.TB_ThongTinThietBi = new HashSet<TB_ThongTinThietBi>();
        }
    
        public int MonHocId { get; set; }
        public string MaMonHoc { get; set; }
        public string Ten { get; set; }
        public Nullable<int> LoaiMonHocId { get; set; }
        public Nullable<int> LoaiDanhGiaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_GiaoVien> DM_GiaoVien { get; set; }
        public virtual DS_LoaiDanhGiaMH DS_LoaiDanhGiaMH { get; set; }
        public virtual DS_LoaiMonHoc DS_LoaiMonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_PhongHocBoMon> DM_PhongHocBoMon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_ThietBiToiThieu> DM_ThietBiToiThieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuMuonPhong> TB_PhieuMuonPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuMuonTB> TB_PhieuMuonTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ThongTinThietBi> TB_ThongTinThietBi { get; set; }
    }
}
