//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MonHoc
    {
        public int MonHocId { get; set; }
        public string MaMonHoc { get; set; }
        public string Ten { get; set; }
        public Nullable<int> LoaiMonHocId { get; set; }
        public Nullable<int> LoaiDanhGiaId { get; set; }
    }
}
