//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NguonKinhPhi
    {
        public int NguonKinhPhiId { get; set; }
        public string Ten { get; set; }
        public Nullable<bool> HasChildren { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> NguonNganSachId { get; set; }
        public string GhiChu { get; set; }
    }
}
