//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NguonKinhPhi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_NguonKinhPhi()
        {
            this.DM_NguonKinhPhi1 = new HashSet<DM_NguonKinhPhi>();
            this.TB_ThongTinThietBi = new HashSet<TB_ThongTinThietBi>();
        }
    
        public int NguonKinhPhiId { get; set; }
        public string Ten { get; set; }
        public Nullable<bool> HasChildren { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> NguonNganSachId { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_NguonKinhPhi> DM_NguonKinhPhi1 { get; set; }
        public virtual DM_NguonKinhPhi DM_NguonKinhPhi2 { get; set; }
        public virtual DS_NguonNganSach DS_NguonNganSach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ThongTinThietBi> TB_ThongTinThietBi { get; set; }
    }
}
