//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PhongHocBoMon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_PhongHocBoMon()
        {
            this.TB_PhieuMuonPhong = new HashSet<TB_PhieuMuonPhong>();
        }
    
        public int PhongHocId { get; set; }
        public string Ten { get; set; }
        public Nullable<int> LoaiPhongTNId { get; set; }
        public Nullable<int> MonHocId { get; set; }
        public Nullable<double> DienTich { get; set; }
        public Nullable<short> SoCanBo { get; set; }
        public Nullable<short> NamDuaVaoSD { get; set; }
        public Nullable<bool> IsPhongChucNang { get; set; }
        public Nullable<int> XepLoaiId { get; set; }
        public int TrangThai { get; set; }
    
        public virtual DM_MonHoc DM_MonHoc { get; set; }
        public virtual DS_LoaiPhongTN DS_LoaiPhongTN { get; set; }
        public virtual DS_XepLoaiPhongHocBM DS_XepLoaiPhongHocBM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuMuonPhong> TB_PhieuMuonPhong { get; set; }
    }
}
