//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_ToBoMon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_ToBoMon()
        {
            this.DM_ToBoMon1 = new HashSet<DM_ToBoMon>();
        }
    
        public int ToBoMonId { get; set; }
        public string Ten { get; set; }
        public Nullable<bool> HasChildren { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string GhiChu { get; set; }
        public string MaBoMon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_ToBoMon> DM_ToBoMon1 { get; set; }
        public virtual DM_ToBoMon DM_ToBoMon2 { get; set; }
    }
}
