//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_ThietBiToiThieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_ThietBiToiThieu()
        {
            this.TB_ThongTinThietBi = new HashSet<TB_ThongTinThietBi>();
        }
    
        public string ThietBiId { get; set; }
        public string Ten { get; set; }
        public int DonViTinhId { get; set; }
        public string DungChoLopHienThi { get; set; }
        public int LoaiThietBiId { get; set; }
        public int MonHocId { get; set; }
        public string MoTa { get; set; }
        public short SoLuong { get; set; }
        public Nullable<int> DauMucId { get; set; }
        public bool IsThuocDMTT { get; set; }
        public bool IsDanhChoGV { get; set; }
        public bool IsDanhChoHS { get; set; }
        public string GhiChu { get; set; }
        public int TrangThai { get; set; }
    
        public virtual DM_MonHoc DM_MonHoc { get; set; }
        public virtual DS_DauMucThietBi DS_DauMucThietBi { get; set; }
        public virtual DS_DonViTinh DS_DonViTinh { get; set; }
        public virtual DS_LoaiThietBi DS_LoaiThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ThongTinThietBi> TB_ThongTinThietBi { get; set; }
    }
}
