//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HT_User()
        {
            this.TB_PhieuThanhLyTB = new HashSet<TB_PhieuThanhLyTB>();
            this.TB_PhieuThanhLyTB1 = new HashSet<TB_PhieuThanhLyTB>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public int UserRoleId { get; set; }
        public Nullable<bool> isActived { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public string Name { get; set; }
    
        public virtual HT_UserRole HT_UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuThanhLyTB> TB_PhieuThanhLyTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuThanhLyTB> TB_PhieuThanhLyTB1 { get; set; }
    }
}
