//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HT_User()
        {
            this.TB_PhieuDeNghiMuaSam = new HashSet<TB_PhieuDeNghiMuaSam>();
            this.TB_PhieuDeNghiMuaSam1 = new HashSet<TB_PhieuDeNghiMuaSam>();
            this.TB_PhieuGhiTang = new HashSet<TB_PhieuGhiTang>();
            this.TB_PhieuGhiTang1 = new HashSet<TB_PhieuGhiTang>();
            this.TB_PhieuGiamTB = new HashSet<TB_PhieuGiamTB>();
            this.TB_PhieuGiamTB1 = new HashSet<TB_PhieuGiamTB>();
            this.TB_PhieuThanhLyTB = new HashSet<TB_PhieuThanhLyTB>();
            this.TB_PhieuThanhLyTB1 = new HashSet<TB_PhieuThanhLyTB>();
            this.TB_ThongTinThietBi = new HashSet<TB_ThongTinThietBi>();
            this.TB_ThongTinThietBi1 = new HashSet<TB_ThongTinThietBi>();
            this.TB_PhieuBaoHong = new HashSet<TB_PhieuBaoHong>();
            this.TB_PhieuBaoHong1 = new HashSet<TB_PhieuBaoHong>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public int UserRoleId { get; set; }
        public Nullable<bool> isActived { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public string Name { get; set; }
    
        public virtual HT_UserRole HT_UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuDeNghiMuaSam> TB_PhieuDeNghiMuaSam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuDeNghiMuaSam> TB_PhieuDeNghiMuaSam1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuGhiTang> TB_PhieuGhiTang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuGhiTang> TB_PhieuGhiTang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuGiamTB> TB_PhieuGiamTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuGiamTB> TB_PhieuGiamTB1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuThanhLyTB> TB_PhieuThanhLyTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuThanhLyTB> TB_PhieuThanhLyTB1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ThongTinThietBi> TB_ThongTinThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ThongTinThietBi> TB_ThongTinThietBi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuBaoHong> TB_PhieuBaoHong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PhieuBaoHong> TB_PhieuBaoHong1 { get; set; }
    }
}
