//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QH_PhieuSuaTB_ThietBi
    {
        public string PhieuSuaTBId { get; set; }
        public string SoHieu { get; set; }
        public int SoLuong { get; set; }
        public int DonViTinhId { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string PhieuBaoHongId { get; set; }
        public string TinhTrangHong { get; set; }
    }
}
