//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QH_PhieuDenNghiMS_ThietBi
    {
        public string PhieuDeNghiId { get; set; }
        public string ThietBiId { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> IsTuMua { get; set; }
    }
}
