//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QH_PhieuKiemKe_ThietBi
    {
        public string SoPhieu { get; set; }
        public string SoHieu { get; set; }
        public int PhongHocId { get; set; }
        public int SoLuong { get; set; }
        public int DonViTinhId { get; set; }
        public int MatTruoc { get; set; }
        public int MatSau { get; set; }
        public int HongTruoc { get; set; }
        public int HongSau { get; set; }
        public int ConDungDuoc { get; set; }
        public int ChenhLechMat { get; set; }
        public int ChenhLechHong { get; set; }
        public string GhiChu { get; set; }
    }
}
