//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QH_PhieuThanhLyTB_ThietBi
    {
        public string PhieuThanhLyTBId { get; set; }
        public string SoHieuTB { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string PhieuBaoHongId { get; set; }
        public string LyDo { get; set; }
    }
}
