//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QH_PhieuBaoHong_ThietBi
    {
        public string PhieuBaoHongId { get; set; }
        public string SoHieuTB { get; set; }
        public int SoLuong { get; set; }
        public string LyDo { get; set; }
        public int TinhTrangId { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual TB_ThongTinThietBi TB_ThongTinThietBi { get; set; }
    }
}
