//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QH_User_Permission
    {
        public int UserRoleId { get; set; }
        public int PermissionId { get; set; }
        public string PermissionKey { get; set; }
        public Nullable<bool> isView { get; set; }
        public Nullable<bool> isAdd { get; set; }
        public Nullable<bool> isUpdate { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual HT_Permission HT_Permission { get; set; }
        public virtual HT_UserRole HT_UserRole { get; set; }
    }
}
