//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Utils;

    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            this.Database.Connection.ConnectionString = ConnectiongStringBuilder.getConnectionString();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DM_CanBoThietBi> DM_CanBoThietBi { get; set; }
        public virtual DbSet<DM_GiaoVien> DM_GiaoVien { get; set; }
        public virtual DbSet<DM_KhoiLop> DM_KhoiLop { get; set; }
        public virtual DbSet<DM_LopHoc> DM_LopHoc { get; set; }
        public virtual DbSet<DM_MonHoc> DM_MonHoc { get; set; }
        public virtual DbSet<DM_NguonKinhPhi> DM_NguonKinhPhi { get; set; }
        public virtual DbSet<DM_PhongHocBoMon> DM_PhongHocBoMon { get; set; }
        public virtual DbSet<DM_ThietBiToiThieu> DM_ThietBiToiThieu { get; set; }
        public virtual DbSet<DM_ToBoMon> DM_ToBoMon { get; set; }
        public virtual DbSet<DS_BaiGiang> DS_BaiGiang { get; set; }
        public virtual DbSet<DS_CapTruong> DS_CapTruong { get; set; }
        public virtual DbSet<DS_ChucVuGiaoVien> DS_ChucVuGiaoVien { get; set; }
        public virtual DbSet<DS_DanToc> DS_DanToc { get; set; }
        public virtual DbSet<DS_DauMucThietBi> DS_DauMucThietBi { get; set; }
        public virtual DbSet<DS_DonViTinh> DS_DonViTinh { get; set; }
        public virtual DbSet<DS_GioiTinh> DS_GioiTinh { get; set; }
        public virtual DbSet<DS_HangTruong> DS_HangTruong { get; set; }
        public virtual DbSet<DS_HinhThucDaoTao> DS_HinhThucDaoTao { get; set; }
        public virtual DbSet<DS_KhoiTruong> DS_KhoiTruong { get; set; }
        public virtual DbSet<DS_LoaiDanhGiaMH> DS_LoaiDanhGiaMH { get; set; }
        public virtual DbSet<DS_LoaiHinhTruong> DS_LoaiHinhTruong { get; set; }
        public virtual DbSet<DS_LoaiHopDong> DS_LoaiHopDong { get; set; }
        public virtual DbSet<DS_LoaiMonHoc> DS_LoaiMonHoc { get; set; }
        public virtual DbSet<DS_LoaiPhongTN> DS_LoaiPhongTN { get; set; }
        public virtual DbSet<DS_LoaiThietBi> DS_LoaiThietBi { get; set; }
        public virtual DbSet<DS_LoaiTruongChuyenBiet> DS_LoaiTruongChuyenBiet { get; set; }
        public virtual DbSet<DS_LyLuanChinhTri> DS_LyLuanChinhTri { get; set; }
        public virtual DbSet<DS_MucDichSDPHong> DS_MucDichSDPHong { get; set; }
        public virtual DbSet<DS_MucDichSDThietBi> DS_MucDichSDThietBi { get; set; }
        public virtual DbSet<DS_NguonNganSach> DS_NguonNganSach { get; set; }
        public virtual DbSet<DS_PhongBan> DS_PhongBan { get; set; }
        public virtual DbSet<DS_PhuongXa> DS_PhuongXa { get; set; }
        public virtual DbSet<DS_PhuTrachCBTB> DS_PhuTrachCBTB { get; set; }
        public virtual DbSet<DS_QuanHuyen> DS_QuanHuyen { get; set; }
        public virtual DbSet<DS_QuanLyGiaoDuc> DS_QuanLyGiaoDuc { get; set; }
        public virtual DbSet<DS_QuanLyNhaNuoc> DS_QuanLyNhaNuoc { get; set; }
        public virtual DbSet<DS_ThoiGianTrongNgay> DS_ThoiGianTrongNgay { get; set; }
        public virtual DbSet<DS_TinhThanh> DS_TinhThanh { get; set; }
        public virtual DbSet<DS_TrangThaiPhieuMuon> DS_TrangThaiPhieuMuon { get; set; }
        public virtual DbSet<DS_TrinhDoChuan> DS_TrinhDoChuan { get; set; }
        public virtual DbSet<DS_TrinhDoChuyenMon> DS_TrinhDoChuyenMon { get; set; }
        public virtual DbSet<DS_ViTriGiaoVien> DS_ViTriGiaoVien { get; set; }
        public virtual DbSet<DS_VungMien> DS_VungMien { get; set; }
        public virtual DbSet<DS_XepLoaiPhongHocBM> DS_XepLoaiPhongHocBM { get; set; }
        public virtual DbSet<HT_User> HT_User { get; set; }
        public virtual DbSet<HT_UserRole> HT_UserRole { get; set; }
        public virtual DbSet<QH_PhieuBaoHong_ThietBi> QH_PhieuBaoHong_ThietBi { get; set; }
        public virtual DbSet<QH_PhieuGiamTB_ThietBi> QH_PhieuGiamTB_ThietBi { get; set; }
        public virtual DbSet<QH_PhieuMuonPhong_ThietBi> QH_PhieuMuonPhong_ThietBi { get; set; }
        public virtual DbSet<QH_PhieuMuonTB_ThietBi> QH_PhieuMuonTB_ThietBi { get; set; }
        public virtual DbSet<QH_PhieuThanhLyTB_ThietBi> QH_PhieuThanhLyTB_ThietBi { get; set; }
        public virtual DbSet<TB_PhieuBaoHong> TB_PhieuBaoHong { get; set; }
        public virtual DbSet<TB_PhieuGiamTB> TB_PhieuGiamTB { get; set; }
        public virtual DbSet<TB_PhieuMuonPhong> TB_PhieuMuonPhong { get; set; }
        public virtual DbSet<TB_PhieuMuonTB> TB_PhieuMuonTB { get; set; }
        public virtual DbSet<TB_PhieuThanhLyTB> TB_PhieuThanhLyTB { get; set; }
        public virtual DbSet<TB_ThongTinThietBi> TB_ThongTinThietBi { get; set; }
        public virtual DbSet<ThongTinDonVi> ThongTinDonVis { get; set; }
    }
}
