//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PhieuSuaTB
    {
        public string PhieuSuaTBId { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string GhiChu { get; set; }
        public int CreatedByUserId { get; set; }
        public int UpdatedByUserId { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.DateTime UpdatedOnDate { get; set; }
    }
}
