//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PhieuBaoHong
    {
        public string PhieuBaoHongId { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string NguoiLamHong { get; set; }
        public string GhiChu { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        public virtual HT_User HT_User { get; set; }
        public virtual HT_User HT_User1 { get; set; }
    }
}
