//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PhieuMuonTB
    {
        public string PhieuMuonTBId { get; set; }
        public string GiaoVienId { get; set; }
        public int MonHocId { get; set; }
        public int KhoiLopId { get; set; }
        public int LopHocId { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public int ThoiGianTrongNgay { get; set; }
        public System.DateTime NgayTra { get; set; }
        public int MucDichSuDungId { get; set; }
        public int SoTiet { get; set; }
        public Nullable<int> BaiDayId { get; set; }
        public bool IsNgoaiQuyDinh { get; set; }
        public int TrangThaiId { get; set; }
        public string GhiChu { get; set; }
        public string CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public string UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual DM_GiaoVien DM_GiaoVien { get; set; }
        public virtual DM_KhoiLop DM_KhoiLop { get; set; }
        public virtual DM_LopHoc DM_LopHoc { get; set; }
        public virtual DM_MonHoc DM_MonHoc { get; set; }
        public virtual DS_BaiGiang DS_BaiGiang { get; set; }
        public virtual DS_MucDichSDThietBi DS_MucDichSDThietBi { get; set; }
        public virtual DS_ThoiGianTrongNgay DS_ThoiGianTrongNgay { get; set; }
        public virtual DS_TrangThaiPhieuMuon DS_TrangThaiPhieuMuon { get; set; }
    }
}
