//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PhieuMuonPhong
    {
        public string PhieuMuonPhongId { get; set; }
        public string GiaoVienId { get; set; }
        public int MonHocId { get; set; }
        public int PhongBoMonId { get; set; }
        public int BaiDayId { get; set; }
        public int KhoiLopId { get; set; }
        public int LopHocId { get; set; }
        public int SoTiet { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public System.DateTime NgayTra { get; set; }
        public bool IsSuDungCaNgay { get; set; }
        public int MucDichSDId { get; set; }
        public bool IsNgoaiQuyDinh { get; set; }
        public bool IsSuDungChoGD { get; set; }
        public Nullable<int> TrangThaiId { get; set; }
        public string GhiChu { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public int ThoiGianTrongNgay { get; set; }
        public int MuonTuTiet { get; set; }
    }
}
