//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ThongTinThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ThongTinThietBi()
        {
            this.QH_PhieuBaoHong_ThietBi = new HashSet<QH_PhieuBaoHong_ThietBi>();
            this.QH_PhieuGhiTang_ThietBi = new HashSet<QH_PhieuGhiTang_ThietBi>();
            this.QH_PhieuGiamTB_ThietBi = new HashSet<QH_PhieuGiamTB_ThietBi>();
            this.QH_PhieuMuonPhong_ThietBi = new HashSet<QH_PhieuMuonPhong_ThietBi>();
            this.QH_PhieuMuonTB_ThietBi = new HashSet<QH_PhieuMuonTB_ThietBi>();
            this.QH_PhieuThanhLyTB_ThietBi = new HashSet<QH_PhieuThanhLyTB_ThietBi>();
        }
    
        public string SoHieu { get; set; }
        public string ThietBiId { get; set; }
        public string Ten { get; set; }
        public string QuyCachSD { get; set; }
        public int PhongHocId { get; set; }
        public Nullable<int> MonHocId { get; set; }
        public int NguonKinhPhiId { get; set; }
        public int NamDuaVaoSD { get; set; }
        public System.DateTime NgayDuaVaoSD { get; set; }
        public int NamTheoDoi { get; set; }
        public int DonViTinhId { get; set; }
        public int SoLuong { get; set; }
        public int SoLuongCon { get; set; }
        public int SoLuongMat { get; set; }
        public int SoLuongHong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string NuocSanXuat { get; set; }
        public int MucDichSDId { get; set; }
        public bool IsThietBiTuLam { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public Nullable<System.DateTime> HanSD { get; set; }
        public string GhiChu { get; set; }
        public int TrangThai { get; set; }
        public Nullable<int> CreateByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    
        public virtual DM_MonHoc DM_MonHoc { get; set; }
        public virtual DM_NguonKinhPhi DM_NguonKinhPhi { get; set; }
        public virtual DM_PhongHocBoMon DM_PhongHocBoMon { get; set; }
        public virtual DM_ThietBiToiThieu DM_ThietBiToiThieu { get; set; }
        public virtual DS_DonViTinh DS_DonViTinh { get; set; }
        public virtual HT_User HT_User { get; set; }
        public virtual HT_User HT_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QH_PhieuBaoHong_ThietBi> QH_PhieuBaoHong_ThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QH_PhieuGhiTang_ThietBi> QH_PhieuGhiTang_ThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QH_PhieuGiamTB_ThietBi> QH_PhieuGiamTB_ThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QH_PhieuMuonPhong_ThietBi> QH_PhieuMuonPhong_ThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QH_PhieuMuonTB_ThietBi> QH_PhieuMuonTB_ThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QH_PhieuThanhLyTB_ThietBi> QH_PhieuThanhLyTB_ThietBi { get; set; }
    }
}
