//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ThongTinThietBi
    {
        public string SoHieu { get; set; }
        public string ThietBiId { get; set; }
        public string Ten { get; set; }
        public string QuyCachSD { get; set; }
        public int PhongHocId { get; set; }
        public int MonHocId { get; set; }
        public int NguonKinhPhiId { get; set; }
        public int NamDuaVaoSD { get; set; }
        public System.DateTime NgayDuaVaoSD { get; set; }
        public int NamTheoDoi { get; set; }
        public int DonViTinhId { get; set; }
        public int SoLuong { get; set; }
        public int SoLuongMuon { get; set; }
        public int SoLuongCon { get; set; }
        public int SoLuongMat { get; set; }
        public int SoLuongHong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string NuocSanXuat { get; set; }
        public int MucDichSDId { get; set; }
        public bool IsThietBiTuLam { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public Nullable<System.DateTime> HanSD { get; set; }
        public string GhiChu { get; set; }
        public int TrangThai { get; set; }
        public Nullable<int> CreateByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
    }
}
