//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTB.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinNamHoc
    {
        public int NamHocId { get; set; }
        public int NamBatDau { get; set; }
        public int NamKetThuc { get; set; }
        public System.DateTime BatDauHK1 { get; set; }
        public System.DateTime BatDauHK2 { get; set; }
        public System.DateTime KetThucNamHoc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
